name = "Sakibul Islam Munna"
rol = "Software Engineer"
email = "sakibul.munnaa@gmail.com"
phone = "+880 1626 246555"
birthday = "December 01, 1998"
location = "New Eskaton, Dhaka, Bangladesh"
avatar = "./config/assets/avatars/my-image.jpg"
username = "sakibul-munna" # <-- github user name
googlemaps = "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d199666.5651251294!2d-121.58334177520186!3d38.56165006739519!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x809ac672b28397f9%3A0x921f6aaa74197fdb!2sSacramento%2C%20CA%2C%20USA!5e0!3m2!1sen!2sbd!4v1647608789441!5m2!1sen!2sbd" 
presentation = """
I am a software engineer with nearly two years of experience. I primarily use Java and Spring Boot, but I am also proficient in JavaScript. 

I am interested in collaborating in software engineering research, focusing on enhancing existing tools and methodologies to reduce the daily struggles of software developers. 
"""
